### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by gulfurs** [gulfurs/P4-Project#1]
#### Description
The main page of the computer interface 

#### Tasks
- [ ] A BPM for the whole track
- [ ] A Volume slider for the whole track
- [ ] Pause + resume + replay from beginning buttons
