### ISSUE TITLE
Block Modification page

### ISSUE THREAD

**Issue by gulfurs** [gulfurs/P4-Project#3]
#### Description
The interface page where the block can be modified, this is both for instruments and drums

#### Tasks
- [ ] Choose different types of instruments
- [ ] Menu for changing the tempo (1/2, 1/4, 1/8...)
- [ ] Menu for filter the signal
